[package]
name = "multer"
version = "0.1.0"
description = "A multipart/form-data parser and writer for tokio.rs in Rust."
homepage = "https://github.com/rousan/multer-rs"
repository = "https://github.com/rousan/multer-rs"
keywords = ["multipart-formdata", "multipart-uploads", "async", "formdata"]
categories = ["asynchronous", "web-programming"]
authors = ["Rousan Ali <hello@rousan.io>"]
readme = "README.md"
license = "MIT"
edition = "2018"

[features]
default = []
json = ["serde", "serde_json"]

[dependencies]
log = "0.4"
bytes = "0.5"
futures = "0.3"
twoway = "0.2"
http = "0.2"
httparse = "1.3"
mime = "0.3"
regex = "1.3"
lazy_static = "1.4.0"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
encoding_rs = "0.8"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
hyper = "0.13"

[[example]]
name = "test"
path = "examples/test.rs"
required-features = ["json"]